name: DevOps Lab CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build Backend
      working-directory: backendsample
      run: |
        npm install
        npm run build || echo "No build step for backend"

    - name: Build Frontend
      working-directory: frontendsample
      run: |
        npm install
        npm run build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Backend Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/fa22-backend:latest backendsample
        docker push $DOCKERHUB_USERNAME/fa22-backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/fa22-frontend:latest frontendsample
        docker push $DOCKERHUB_USERNAME/fa22-frontend:latest

    # Optional: Deploy to Kubernetes / staging
    # You can add kubectl steps here later